-- MySQL Script generated by MySQL Workbench
-- Mon Nov 21 20:24:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbferreteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbferreteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbferreteria` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `dbferreteria` ;

-- -----------------------------------------------------
-- Table `dbferreteria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbferreteria`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `descripcion` VARCHAR(255) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 18;


-- -----------------------------------------------------
-- Table `dbferreteria`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbferreteria`.`articulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `codigo` VARCHAR(50) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `nombre` VARCHAR(100) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `precio_venta` DECIMAL(11,2) NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(255) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `imagen` VARCHAR(50) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_articulo_categoria_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_articulo_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `dbferreteria`.`categoria` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12;


-- -----------------------------------------------------
-- Table `dbferreteria`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbferreteria`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_persona` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `nombre` VARCHAR(70) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `tipo_documento` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `num_documento` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `direccion` VARCHAR(70) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `telefono` VARCHAR(15) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `email` VARCHAR(50) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7;


-- -----------------------------------------------------
-- Table `dbferreteria`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbferreteria`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `descripcion` VARCHAR(255) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `dbferreteria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbferreteria`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol_id` INT NOT NULL,
  `nombre` VARCHAR(70) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `tipo_documento` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `num_documento` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `direccion` VARCHAR(70) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `telefono` VARCHAR(15) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `email` VARCHAR(50) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `clave` VARCHAR(128) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_rol_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `dbferreteria`.`rol` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `dbferreteria`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbferreteria`.`ingreso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `serie_comprobante` VARCHAR(7) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `num_comprobante` VARCHAR(10) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `fecha` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NOT NULL DEFAULT 'Aceptado',
  PRIMARY KEY (`id`),
  INDEX `fk_ingreso_persona_idx` (`persona_id` ASC) VISIBLE,
  INDEX `fk_ingreso_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingreso_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `dbferreteria`.`persona` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_ingreso_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `dbferreteria`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13;


-- -----------------------------------------------------
-- Table `dbferreteria`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbferreteria`.`detalle_ingreso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingreso_id` INT NOT NULL,
  `articulo_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_ingreso_ingreso_idx` (`ingreso_id` ASC) VISIBLE,
  INDEX `fk_detalle_ingreso_articulo_idx` (`articulo_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_ingreso_articulo`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `dbferreteria`.`articulo` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_detalle_ingreso_ingreso`
    FOREIGN KEY (`ingreso_id`)
    REFERENCES `dbferreteria`.`ingreso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14;


-- -----------------------------------------------------
-- Table `dbferreteria`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbferreteria`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `serie_comprobante` VARCHAR(7) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `num_comprobante` VARCHAR(10) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `fecha` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) COLLATE 'utf8mb3_spanish_ci' NOT NULL DEFAULT 'Aceptado',
  PRIMARY KEY (`id`),
  INDEX `fk_ingreso_persona_idx` (`persona_id` ASC) VISIBLE,
  INDEX `fk_venta_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_venta_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `dbferreteria`.`persona` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_venta_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `dbferreteria`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `dbferreteria`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbferreteria`.`detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `articulo_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  `descuento` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_venta_venta_idx` (`venta_id` ASC) VISIBLE,
  INDEX `fk_detalle_venta_articulo_idx` (`articulo_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_venta_articulo`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `dbferreteria`.`articulo` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_detalle_venta_venta`
    FOREIGN KEY (`venta_id`)
    REFERENCES `dbferreteria`.`venta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7;

USE `dbferreteria`;

DELIMITER $$
USE `dbferreteria`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `dbsistema`.`tr_updateStockIngresoAnular`
AFTER UPDATE ON `dbsistema`.`ingreso`
FOR EACH ROW
begin
	update articulo a 
	join detalle_ingreso di
	on di.articulo_id = a.id
	and di.ingreso_id = new.id
	set a.stock = a.stock - di.cantidad;
END$$

USE `dbferreteria`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `dbsistema`.`tr_updateStockIngreso`
AFTER INSERT ON `dbsistema`.`detalle_ingreso`
FOR EACH ROW
BEGIN
 UPDATE articulo SET stock = stock + NEW.cantidad 
 WHERE articulo.id = NEW.articulo_id;
END$$

USE `dbferreteria`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `dbsistema`.`tr_updateStockVentaAnular`
AFTER UPDATE ON `dbsistema`.`venta`
FOR EACH ROW
begin
    update articulo a
    join detalle_venta dv
    on dv.articulo_id = a.id
    and dv.venta_id = NEW.id
    set a.stock = a.stock + dv.cantidad;
END$$

USE `dbferreteria`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `dbsistema`.`tr_updateStockVenta`
AFTER INSERT ON `dbsistema`.`detalle_venta`
FOR EACH ROW
begin
    update articulo set stock = stock - NEW.cantidad
    where articulo.id = NEW.articulo_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
